version: "3.9"
services:

  mqttx:
    image: emqx/mqttx-web:latest
    container_name: mqttx
    ports:
      - 80:80
    # docker run -d --name mqttx-web -p 80:80 

  nanomq:
    image: emqx/nanomq:0.18.2-slim
    container_name: nanomq
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
    volumes:
      - ./mqtt/nanomq.conf:/etc/nanomq.conf

  frigate:
    container_name: frigate
    restart: unless-stopped
    build: .
    # image: ghcr.io/blakeblackshear/frigate:stable
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    # command: [ "python3", "/mqtt/mqtt_events_listener.py" ]
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      # - ./mqtt:/mqtt
      - /etc/localtime:/etc/localtime
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1935:1935"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  mqtt_events_listener:
    container_name: mqtt_events_listener
    restart: unless-stopped
    build: ./mqtt
    command: [ "python3", "/mqtt/mqtt_events_listener.py" ]
    volumes:
      - ./mqtt:/mqtt
