services:

  nanomq:
    image: emqx/nanomq:0.18.2-slim
    container_name: nanomq
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
    volumes:
      - ./nanomq/nanomq.conf:/etc/nanomq.conf

  frigate:
    container_name: frigate
    restart: unless-stopped
    build: .
    shm_size: '192mb'
    # image: ghcr.io/blakeblackshear/frigate:stable
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - YOLO_MODELS=yolov7-640
    # command: [ "python3", "/mqtt/mqtt_events_listener.py" ]
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      # - ./mqtt:/mqtt
      - /etc/localtime:/etc/localtime
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1935:1935"
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "1984:1984"
      # - "8555:8555/tcp" # WebRTC over tcp
      # - "8555:8555/udp" # WebRTC over udp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  mqtt_events_listener:
    container_name: mqtt_events_listener
    restart: unless-stopped
    build: ./mqtt
    environment:
      - PYTHONPATH=/mqtt/speed_estimation
      # - PYTHONPATH=/mqtt
    command: [ "python3", "/mqtt/mqtt_events_listener.py" ]
    volumes:
      - ./mqtt:/mqtt
      - ./config/config.yml:/mqtt/config.yml
      - /etc/localtime:/etc/localtime
      - ./storage/speed_estimation:/storage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  # mediamtx:
  #   platform: linux/amd64
  #   container_name: mediamtx-server
  #   image: bluenviron/mediamtx:latest-ffmpeg
  #   environment:
  #     - RTSP_PROTOCOLS=tcp
  #   # volumes:
  #   #   - ./mediamtx/mediamtx.yml:/mediamtx.yml
  #   ports:
  #     - 8189:8189
  #     - 8889:8889
  #     - 8854:8554
  #   restart: unless-stopped
