services:

  mqtt_events_listener:
    container_name: mqtt_events_listener
    restart: unless-stopped
    build: ./mqtt
    environment:
      - PYTHONPATH="/mqtt/speed_estimation:/mqtt/speed_estimation/tg_bot:$PYTHONPATH"
      # - PYTHONPATH=/mqtt
    command: [ "python3", "/mqtt/mqtt_events_listener.py" ]
    volumes:
      - ./mqtt:/mqtt
      - /etc/localtime:/etc/localtime
      - ./speed_estimation:/storage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  filebrowser:
    container_name: filebrowser
    restart: unless-stopped
    image: filebrowser/filebrowser
    volumes:
      - ./speed_estimation:/srv
      - ./filebrowser/filebrowser.db:/database.db
      # - ./filebrowser/.filebrowser.json:/.filebrowser.json
    ports:
      - 80:80

  mqtt_notificator:
    container_name: mqtt_notificator
    restart: unless-stopped
    build: ./mqtt_notificator
    command: [ "python3", "/mqtt_notificator/demo_script.py" ]
    volumes:
      - ./mqtt_notificator:/mqtt_notificator
      - /etc/localtime:/etc/localtime
      - ./speed_estimation:/storage