version: "3.9"
services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    build: .
    # image: ghcr.io/blakeblackshear/frigate:stable
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    command: [ "python3", "/config/db.py", "120" ] # - "pip install --upgrade openvino"
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - /etc/localtime:/etc/localtime
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
