services:

  mqtt_events_listener:
    container_name: mqtt_events_listener
    restart: unless-stopped
    build: ./mqtt
    environment:
      - PYTHONPATH=/mqtt/speed_estimation
      # - PYTHONPATH=/mqtt
    command: [ "python3", "/mqtt/mqtt_events_listener.py" ]
    volumes:
      - ./mqtt:/mqtt
      - /etc/localtime:/etc/localtime
      - ./speed_estimation:/storage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  