services:

  # nanomq:
  #   image: emqx/nanomq:0.18.2-slim
  #   container_name: nanomq
  #   restart: unless-stopped
  #   ports:
  #     - 1883:1883
  #     - 8083:8083
  #     - 8883:8883
  #   volumes:
  #     - ./nanomq/nanomq.conf:/etc/nanomq.conf

  mediamtx:
    platform: linux/amd64
    container_name: mediamtx-server
    image: bluenviron/mediamtx:latest-ffmpeg
    environment:
      - RTSP_PROTOCOLS=tcp
      - TZ="Europe/Moscow"
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
     - 8189:8189
     - 8889:8889/udp
     - 8889:8889/tcp
     - 8554:8554
     - 8555:8555/udp
    restart: unless-stopped

  frigate:
    container_name: frigate
    restart: unless-stopped
    privileged: true
    shm_size: '192mb'
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - /etc/localtime:/etc/localtime
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "1935:1935"
      - "5000:5000"
      # - "8554:8554" # RTSP feeds
      - "1984:1984"
    # devices:
    #   - "/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]
