# go2rtc:
#   rtsp:
#     listen: ":8554"    # RTSP Server TCP port, default - 8554
#     streams:
#       test: # <- for RTSP streams
#         - rtsp://mediamtx-server:8554/stream0.sdp
#         # - ffmpeg:#yuv420p
#         - ffmpeg:test#video=h264#video=mjpeg
#         # - ffmpeg:rtsp://admin:admin@192.168.0.39:8854#video=h264#video=mjpeg

birdseye:
  restream: true

mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: true
  # Required: host name
  host: nanomq
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: user
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: user
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    # - person
    - forklift

    # - каска
    # - нет-каски
    # - нет-жилета
    # - человек
    # - жилет
    # - погрузчик

    # - helmet
    # - no_helmet
    # - no_vest
    # - person
    # - vest
    # - forklift
    
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      # min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      # max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      # min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      # max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      # mask:
      #   - 0,480,341,480,347,0,0,0
    helmet:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.55
      # mask:
      #   - 0,480,341,480,347,0,0,0
    no-helmet:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.55
    no-vest:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.55
    vest:
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.55
      # mask:
      #   - 0,480,341,480,347,0,0,0


detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      # path: /config/yolov8/yolov8n.xml
      # path: /config/hf/hf.xml
      # path: /config/helmets/helmets.xml
      # path: /config/human_forklift_helmet_vest/human_forklift_helmet_vest.xml
      # path: /config/yolov9c/yolov9c.xml
      # path: /config/clips_model/clips_model.xml
      path: /config/clips_model_v2/clips_model_v2.xml

model:
  width: 640
  height: 640
  input_tensor: nchw
  input_pixel_format: bgr
  model_type: yolov8
  # labelmap_path: /config/yolov8/coco_80cl.txt
  # labelmap_path: /config/hf/hf_labelmap.txt
  # labelmap_path: /config/helmets/helmets_labelmap.txt
  # labelmap_path: /config/human_forklift_helmet_vest/human_forklift_helmet_vest_labelmap.txt
  # labelmap_path: /config/yolov9c/yolov9c_labelmap.txt
  # labelmap_path: /config/clips_model/clips_model_labelmap.txt
  labelmap_path: /config/clips_model_v2/clips_model_v2_labelmap.txt

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: false
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 3
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: all
  # Optional: Recording Export Settings
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.04*PTS -r 30
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    # objects:
    #   - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    # required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 10
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: motion
      # Optional: Per object retention days
      # objects:
      #   person: 15

cameras:
  test:
    enabled: true

    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        # - path: rtsp://admin:admin@192.168.0.39:1935
        # # - path: http://192.168.0.39:8080/video
        # #   input_args: -re -stream_loop -1 -fflags +genpts
        #   roles:
        #     - detect
        #     - record

        - path: rtsp://192.168.11.2:554/user=admin&password=Zse45rdx&channel=1&stream=0.sdp?real_stream
        # - path: rtsp://mediamtx-server:8554/stream0.sdp
          # input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    zones:
      # zone_0:
      #   coordinates: 689,203,684,79,544,62
      zone_1:
        coordinates: 0,480,341,480,347,0,0,0
        # Optional: Number of consecutive frames required for object to be considered present in the zone (default: shown below).
        inertia: 5

  # test2:
  #   enabled: true

  #   ffmpeg:
  #     hwaccel_args: preset-nvidia-h264
  #     inputs:
  #       - path: rtsp://admin:Zse45rdx@192.168.71.7:554/ISAPI/Streaming/Channels/01
  #         roles:
  #           - record
  #           - detect
