# go2rtc:
#   rtsp:
#     listen: ":8554"    # RTSP Server TCP port, default - 8554
#     streams:
#       test: # <- for RTSP streams
#         - rtsp://mediamtx-server:8554/stream0.sdp
#         # - ffmpeg:#yuv420p
#         - ffmpeg:test#video=h264#video=mjpeg
#         # - ffmpeg:rtsp://admin:admin@192.168.0.39:8854#video=h264#video=mjpeg

birdseye:
  restream: true

mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: true
  # Required: host name
  host: nanomq
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # NOTE: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  # NOTE: MQTT user can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. user: '{FRIGATE_MQTT_USER}'
  user: user
  # Optional: password
  # NOTE: MQTT password can be specified with an environment variable or docker secrets that must begin with 'FRIGATE_'.
  #       e.g. password: '{FRIGATE_MQTT_PASSWORD}'
  password: user
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

detect:
  # Optional: width of the frame for the input with the detect role (default: use native stream resolution)
  width: 1920
  # Optional: height of the frame for the input with the detect role (default: use native stream resolution)
  height: 1080
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  enabled: true
  # Optional: Number of consecutive detection hits required for an object to be initialized in the tracker. (default: 1/2 the frame rate)
  min_initialized: 2
  # Optional: Number of frames without a detection before Frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 100
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: same as threshold)
    # When set to 1, object detection will run to confirm the object still exists on every frame.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
    interval: 50
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
      default: 3000
  # Optional: Milliseconds to offset detect annotations by (default: shown below).
  # There can often be latency between a recording and the detect process,
  # especially when using separate streams for detect and record.
  # Use this setting to make the timeline bounding boxes more closely align
  # with the recording. The value can be positive or negative.
  # TIP: Imagine there is an event clip with a person walking from left to right.
  #      If the event timeline bounding box is consistently to the left of the person
  #      then the value should be decreased. Similarly, if a person is walking from
  #      left to right and the bounding box is consistently ahead of the person
  #      then the value should be increased.
  # TIP: This offset is dynamic so you can change the value and it will update existing
  #      events, this makes it easy to tune.
  # WARNING: Fast moving objects will likely not have the bounding box align.
  annotation_offset: 0

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - forklift
    # - cabledrum
  filters:
    forklift:
      min_area: 100
      min_score: 0.8
    cabledrum:
      min_area: 100
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      # min_area: 5000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      # max_area: 100000
      # Optional: minimum width/height of the bounding box for the detected object (default: 0)
      # min_ratio: 0.5
      # Optional: maximum width/height of the bounding box for the detected object (default: 24000000)
      # max_ratio: 2.0
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      # mask:
      #   - 0,480,341,480,347,0,0,0

detectors:
  onnx:
    type: onnx

model:
  model_type: rfdetr
  width: 640
  height: 640
  input_tensor: nchw
  input_dtype: float
  path: /config/forklift.onnx
  labelmap:
    0: forklift
    1: cabledrum

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via
  #          the UI or MQTT later will have no effect.
  enabled: true
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Sync recordings with disk on startup and once a day (default: shown below).
  sync_recordings: false
  # Optional: Retention settings for recording
  export:
    # Optional: Timelapse Output Args (default: shown below).
    # NOTE: The default args are set to fit 24 hours of recording into 1 hour playback.
    # See https://stackoverflow.com/a/58268695 for more info on how these args work.
    # As an example: if you wanted to go from 24 hours to 30 minutes that would be going
    # from 86400 seconds to 1800 seconds which would be 1800 / 86400 = 0.02.
    # The -r (framerate) dictates how smooth the output video is.
    # So the args would be -vf setpts=0.02*PTS -r 30 in that case.
    timelapse_args: -vf setpts=0.04*PTS -r 30
  # Optional: Event recording settings
  alerts:
    retain: {}
    pre_capture: 5
    post_capture: 5
  detections:
    retain: {}
    pre_capture: 5
    post_capture: 5

cameras:
  Reg13_cam19:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://192.168.11.2:554/user=admin&password=Zse45rdx&channel=1&stream=0.sdp?real_stream
          roles:
            - record
            - detect
    zones:
      zone_0:
        coordinates: 0.117,0.98,0.335,0.848,0.048,0.205,0.028,0.21
        # Optional: Number of consecutive frames required for object to be considered present in the zone (default: shown below).
        inertia: 5
        loitering_time: 0
      zone_1:
        coordinates: 0.117,1,0.589,1,0.061,0.183,0.021,0.199
        inertia: 3
        loitering_time: 0
      zone_2:
        coordinates: 0.485,1,0.994,0.419,0.88,0.37,0,1
        inertia: 3
        loitering_time: 0
    objects:
      filters:
        forklift:
          mask: 0.184,0.156,0.057,0.208,0.335,0.853,0.875,0.375

  Reg05_cam32:
    enabled: true

    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:Zse45rdx@192.168.71.178:554/ISAPI/Streaming/Channels/01
          roles:
            - record
            - detect
    zones:
      zone_0:
        coordinates: 810,918,447,1039,410,117,444,110
      zone_1:
        coordinates: 423,1080,1250,1080,490,197,401,215
      zone_2:
        coordinates: 408,343,527,1080,0,1080,97,403
      zone_3:
        coordinates: 1621,411,1920,573,1220,1080,866,709

  # Reg02_cam13:
  #   enabled: true

  #   ffmpeg:
  #     hwaccel_args: preset-nvidia-h264
  #     inputs:
  #     - path: rtsp://admin:Zse45rdx@192.168.11.36:554/ISAPI/Streaming/Channels/01
  #       roles:
  #       - record
  #       - detect

  #   zones:
  #     zone_0:
  #       coordinates: 1754,194,1852,227,550,989,120,587
  #     zone_1:
  #       coordinates: 750,983,1837,246,1738,210,0,679
  #     zone_2:
  #       coordinates: 0,1080,801,1080,786,912,0,659

  Reg04_cam07:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:Zse45rdx@192.168.71.7:554/ISAPI/Streaming/Channels/01
          roles:
            - record
            - detect
    zones:
      zone_0:
        coordinates: 128,975,399,898,79,76,37,78
      zone_1:
        coordinates: 51,1080,690,1080,101,141,25,146
      zone_2:
        coordinates: 130,1080,1407,603,1083,412,0,531

  Reg02_cam17:
    enabled: true

    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:Zse45rdx@192.168.11.178:554/ISAPI/Streaming/Channels/01
          roles:
            - record
            - detect
    zones:
      zone_0:
        coordinates: 262,880,1659,217,1579,173,243,660
      zone_1:
        coordinates: 25,1080,1733,254,1493,144,0,626

  Reg06_cam25:
    enabled: true
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:Zse45rdx@192.168.71.79:554/ISAPI/Streaming/Channels/01
          roles:
            - record
            - detect
    zones:
      zone_0:
        coordinates: 1112,861,176,158,124,170,545,1080
      zone_1:
        coordinates: 1920,1080,328,233,140,259,348,1080
      zone_2:
        coordinates: 1920,1080,1920,724,738,305,510,359

version: 0.16-0
